#!/bin/bash

cd
cd /dev
list=`ls sd?`
x=`echo $list | awk '{print $1}'`
sudo umount $x*1
sudo parted -s /dev/$x mkfs 1 FAT32
sudo mount /dev/$x*1 /media/SD1
sudo cp -r /home/pi/prova/prova2 /media/SD1
sudo umount /media/SD1
