#!/bin/bash

cd /dev
list=`ls sd?`
x=`echo $list | awk '{print $1}'`
sudo umount $x*1
sudo parted -s /dev/$x unit MB resize 1 0 2000
sudo parted -s /dev/$x mkfs 1 FAT16
sudo mount /dev/$x*1 /media/SD1
sudo cp -r /home/pi/BCN3DSigmaScreen/. /media/SD1
sudo umount /media/SD1
