#!/bin/bash

cd
cd /dev
list=`ls sd?`
x=`echo $list | awk '{print $2}'`
sudo umount $x*1
sudo parted -s /dev/$x mkfs 1 FAT32
sudo mount /dev/$x*1 /media/SD2
sudo cp -rfv /home/pi/BCN3DPlus/* /media/SD2
sudo umount /media/SD2
