#!/bin/bash

cd
cd /dev
list=`ls sd?`
x=`echo $list | awk '{print $3}'`
sudo umount $x*1
sudo parted -s /dev/$x mkfs 1 FAT32
sudo mount /dev/$x*1 /media/SD3
sudo cp -r /home/pi/BCN3DPlus /media/SD3
sudo umount /media/SD3
