#!/bin/bash

cd /dev
list=`ls sd?`
x=`echo $list | awk '{print $6}'`
sudo umount $x*1
sudo parted -s /dev/$x unit MB resize 1 0 2000
sudo parted -s /dev/$x mkfs 1 FAT16
sudo mount /dev/$x*1 /media/SD6
sudo cp -rfv /home/pi/BCN3DSigmaScreen/* /media/SD6
sudo umount /media/SD6

