#!/bin/bash

cd /dev
list=`ls sd?`
x=`echo $list | awk '{print $7}'`
sudo umount $x*1
sudo parted -s /dev/$x mkfs 1 FAT32
sudo mount /dev/$x*1 /media/SD7
sudo cp -rfv /home/pi/BCN3DSigma/* /media/SD7
sudo umount /media/SD7

