#!/bin/bash

cd /dev
list=`ls sd?`
x=`echo $list | awk '{print $8}'`
sudo umount $x*1
sudo parted -s /dev/$x mkfs 1 FAT32
sudo mount /dev/$x*1 /media/SD8
sudo cp -r /home/pi/BCN3DSigma /media/SD8
sudo umount /media/SD8

